language: elixir
elixir:
  - 1.3.4
dist: trusty
otp_release:
  - 18.3
sudo: false
env:
  - MIX_ENV=test
  - MIX_ENV=test ELIXIR_ERL_OPTIONS="+T 9"
before_script:
  - mix compile --warnings-as-errors
  - mix dialyzer.plt
script:
  - mix coveralls.travis
  - mix dialyzer --halt-exit-status
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - .dialyxir
    - _build
    - deps
addons:
  apt:
    packages:
    - libcap-dev
